### ISSUE TITLE
Location?

### ISSUE THREAD

**Issue by fromEON** [ShigetoMaeda/autofocus_vr_eevee#1]
Will it input key frames Location data of object/camera  or only rotation?

**Comment by ShigetoMaeda** [comment]
You can move the object ‘camera_head‘ to move with Keyframe animation. The ’right_camera’ is linked to the ‘camera_head’. The rotation data is send to ‘right_camera’. If you’d like to use dual (right and left) camera, please add and link left camera, and move ‘camera_head’ object.
